// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqyxycyohmbyhngvvtgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xeXh5Y3lvaG1ieWhuZ3Z2dGd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MjIyNjIsImV4cCI6MjA2MjE5ODI2Mn0.36F7Mmn3Ie-FLKbd41uIDlzdSxupmkaZI8eQm2yDoFY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);